# Generated by Django 4.2.6 on 2023-10-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('escuela', models.CharField(max_length=20)),
                ('anio', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='year.year')),
            ],
        ),
    ]
