# Generated by Django 4.2.6 on 2023-10-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0002_alter_profesor_titulo'),
        ('year', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='materia.materia')),
                ('profesor', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='profesor.profesor')),
                ('year', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='year.year')),
            ],
        ),
    ]
