# Generated by Django 4.2.6 on 2023-10-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesor_materia', '0002_remove_profesor_materia_year_profesor_materia_nivel'),
        ('alumno', '0001_initial'),
        ('clase_particular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase_particular',
            name='alumno',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='alumno.alumno'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='clase_particular',
            name='comentarios',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase_particular',
            name='profesor_materia',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='profesor_materia.profesor_materia'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='clase_particular',
            name='hora_fin',
            field=models.TimeField(),
        ),
    ]
