# Generated by Django 4.2.6 on 2023-10-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='descripcion',
            field=models.CharField(max_length=30),
        ),
    ]
